engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

ratings:
  paths:
    - "packages/**/*.ts"

exclude_paths:
  - "**/examples/"
  - "**/build/"
  - "**/docs/"
  - "**/*.spec.ts"
  - "**/*.d.ts"
