engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
    - "src/**"

exclude_paths:
 - "demo/*"
 - "docs/*"
 - "gulp/*"
 - "test/*"
 - "gulpfile.js"
 - "karma.conf.js"
