engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

plugins:
  eslint:
    enabled: true
    channel: eslint-5

ratings:
  paths:
    - "packages/**/*.ts"

exclude_paths:
  - "**/examples/"
  - "**/build/"
  - "**/docs/"
  - "**/_*"
  - "**/*.spec.ts"
  - "**/*.d.ts"
