extends:
  - 'standard'

env:
  commonjs: true
  es6: true
  node: true

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  ecmaVersion: 2018

plugins:
  - '@typescript-eslint'

rules:
  brace-style: 0
  comma-dangle: [2, 'always-multiline']
  comma-style: [2, last]
  guard-for-in: 0
  key-spacing: 0
  linebreak-style: [2, unix]
  no-caller: 2
  no-console: 0
  no-empty: 0
  no-multi-spaces: 0
  no-shadow: 2
  no-useless-constructor: 0
  no-var: 2
  node/no-extraneous-import: [2, { allowModules: ['@interactjs/_dev'] }]
  node/no-missing-import: 2
  node/no-unsupported-features/es-syntax: 0
  prefer-arrow-callback: [2, { allowNamedFunctions: true }]
  prefer-const: 2
  standard/array-bracket-even-spacing: 0
  standard/computed-property-even-spacing: 0
  standard/object-curly-even-spacing: 0

overrides:
  files: '*.ts'
  rules:
    no-unused-vars: 0
    no-use-before-define: 0
    node/no-missing-import: 0
