extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'

env:
  commonjs: true
  es6: true
  node: true

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  ecmaVersion: 2018

plugins:
  - '@typescript-eslint'

rules:
  comma-dangle: 0
  comma-style: [2, last]
  curly: 2
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  guard-for-in: 0
  indent: [2, 2]
  keyword-spacing: [2, { before: true, after: true }]
  linebreak-style: [2, unix]
  no-caller: 2
  no-console: 0
  no-empty: 0
  no-extra-bind: 2
  no-extra-semi: 0
  no-self-compare: 2
  no-sequences: 2
  no-shadow-restricted-names: 2
  no-shadow: 2
  no-trailing-spaces: 2
  no-unused-expressions: 2
  no-var: 2
  node/no-extraneous-import: [2, { allowModules: ['@interactjs/_dev'] }]
  node/no-missing-import: 2
  node/no-unsupported-features/es-syntax: 0
  one-var: [2, never]
  prefer-const: 2
  quotes: [2, single, avoid-escape]
  semi: 0
  space-before-function-paren: [2, always]

overrides:
  files: '*.ts'
  rules:
    no-unused-vars: 0
